weechat scripts

These synced to the upstream repository at:

  http://git.savannah.gnu.org/gitweb/?p=weechat/scripts.git

With some local additions and modifications.

* New scripts

** emote

This script provides a buffer of emoji and a mechanism to insert them by name into the buffer.

For example, 

#+BEGIN_EXAMPLE
/key bind meta-e /emote list
M-e smile ENTER
:)
#+END_EXAMPLE

Then when you hit =M-e= you will be taken to the "emote" buffer where you can see the available emoji.  Type the name of the one you want and hit =ENTER= and it will be inserted into the input on the original buffer.  

** bee

This script provides spelling suggestions.  It requires [[http://packages.python.org/pyenchant/][PyEnchant]].

To use it bind the =/bee= command to a key.  Eg via:

#+BEGIN_EXAMPLE
/key bind alt-g /bee 
#+END_EXAMPLE

Then when this key is hit a bar will be shown with spelling
suggestions for the word under the cursor.

* Modified scripts

** urlbar

Reverse the numbering in the displayed URLs in the urlbar.  Add a =load= command:

#+BEGIN_EXAMPLE
/urlbar load [n]
#+END_EXAMPLE

This loads the n^th URL.  If no number is given then the most recent
URL is loaded.  A suggestion is to alias it:

#+BEGIN_EXAMPLE
/alias ul /urlbar load
#+END_EXAMPLE

then a quick =/ul= will load the just posted URL.

Make the format for the urlbar be configurable with the =show_format=
option.  Python interpolation using information about the collected
URL can be used.  For example:

#+BEGIN_EXAMPLE
/set plugins.var.python.urlbar.show_format "%(time)s %(buffername)16s %(nick)16s %(url)s"
/save
#+END_EXAMPLE
